use crate::model::TaskTemplate;

pub const BUILTIN_TEMPLATES: &[TaskTemplate] = &[
    TaskTemplate {
        id: "service-docs-to-wiki",
        name: "Service Docs → Wiki",
        description: "Write service documentation to wiki when a new repo is created",
        icon: "📝",
        source_service: "Forgejo",
        source_offer: "repos.list",
        target_service: "Outline",
        target_accept: "document.create",
    },
    TaskTemplate {
        id: "new-user-welcome",
        name: "New User Welcome",
        description: "Send welcome message when a new user is created in Kanidm",
        icon: "👋",
        source_service: "Kanidm",
        source_offer: "users.list",
        target_service: "Broadcast Bot",
        target_accept: "message.send",
    },
    TaskTemplate {
        id: "daily-task-digest",
        name: "Daily Task Digest",
        description: "Send daily overdue tasks summary via chat",
        icon: "📊",
        source_service: "Vikunja",
        source_offer: "tasks.overdue",
        target_service: "Broadcast Bot",
        target_accept: "message.send",
    },
    TaskTemplate {
        id: "commit-changelog",
        name: "Commit → Wiki Changelog",
        description: "Write git commits to wiki changelog page",
        icon: "📋",
        source_service: "Forgejo",
        source_offer: "commits.recent",
        target_service: "Outline",
        target_accept: "document.update",
    },
    TaskTemplate {
        id: "login-alert",
        name: "Login Alert",
        description: "Alert on failed login attempts",
        icon: "🔐",
        source_service: "Kanidm",
        source_offer: "login.recent",
        target_service: "Broadcast Bot",
        target_accept: "message.send",
    },
];
